### ISSUE TITLE
Treatment of variance [STAT] cubes

### ISSUE THREAD

**Issue by Azeret** [ktsoto/zap#4]
It seems the ZAP does not apply to variance [STAT] cubes, only to the data ones. 
Is there a way to change this? 
After running the ZAP it results in original (therefore very large) variance [STAT] cubes that prevents usage and further analysis. 

Thank you for response! 
Tereza (tjerabko(at)eso.org)

**Comment by saimn** [comment]
This issue was moved to musevlt/zap#5
